apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tf2-rs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: tf2-rs-az.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tf2-rs
                port:
                  number: 80